language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "arun-johnson-github"
    token:
      secure: "9e407ac32d6a6da98970e23542eaceb9bb44616f"
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    
language: java    
jdk:
  - oraclejdk8

services:
  - mysql

script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
notifications:
  email:
    recipients:
      - arun.johnson@lxisoft.com
    on_success: always # default: change
    on_failure: always # default: always
    
 webhooks:
    - secure: "9e407ac32d6a6da98970e23542eaceb9bb44616f"
  on_start: always
